dist: trusty
language: node_js
node_js:
  - "7"
addons:
  firefox: "45.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm run rollup_tests
script:
  # Tests should work
  - npm test
  # Types should be OK
  - |
    mv tsconfig.json tsconfig.ignore
    node_modules/.bin/tsc --target ES2015 --noEmit src/main.ts
    mv tsconfig.ignore tsconfig.json
  # Building a distribution should work
  - npm run dist
